[package]

name = "conduit-conditional-get"
version = "0.9.0-alpha.3"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT"
description = """
Middleware to transform GET into a conditional response if headers indicate that
the response is fresh.
"""

[dependencies]
conduit = "0.9.0-alpha.2"
conduit-middleware = "0.9.0-alpha.4"
time = { version = "0.2", default-features = false, features = ["std"] }

[dev-dependencies]
conduit-test = "0.9.0-alpha.2"
